[package]
name = "kiro"
version = "0.1.0"
authors = ["narpfel <narpfel@gmx.de>"]
edition = "2018"

[profile.release]
lto = true

[dependencies]
libc = "0.2"

[build-dependencies]
cc = "1"
cbindgen = "0.14"
