language = "C"

include_guard = "KIRO_H"

sys_includes = ["time.h"]

[export]
include = ["Row", "Editor"]

[export.rename]
Row = "erow"
Editor = "editorConfig"

[parse]
parse_deps = true
include = ["kiro"]
