language = "C"

include_guard = "KIRO_H"

[export]
include = ["Syntax", "Row", "Colour", "Editor"]

[export.rename]
Syntax = "editorSyntax"
Colour = "hlcolor"
Row = "erow"
Editor = "editorConfig"

[parse]
parse_deps = true
include = ["kiro"]
