language = "C"

include_guard = "KIRO_H"

[export]
include = ["Row", "Editor"]
exclude = ["Status"]

[export.rename]
Row = "erow"
Editor = "editorConfig"

Status = "void"

[parse]
parse_deps = true
include = ["kiro"]
