name: CI

on:
  push:
    branches: [ master ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        profile:
          - name: dev
            flag: ""
          - name: release
            flag: --release
        os:
          - ubuntu-20.04
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - name: Build (${{ matrix.profile.name }})
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: ${{ matrix.profile.flag }}

  pre-commit:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: clippy, rustfmt
      - uses: actions/setup-python@v1
      - uses: pre-commit/action@v2.0.0
